platform :ios, :deployment_target => "7.0"
pod 'MMDrawerController', '~> 0.5.0'
pod 'AFNetworking'
pod 'MBProgressHUD'
pod 'ISRefreshControl', '~> 1.0.2'
pod 'CXFeedParser'
pod 'REMenu', '~> 1.5'
pod 'SDWebImage'
pod 'STTwitter'
pod 'MZDayPicker', '~> 0.0.5'
pod 'PBWebViewController' 
pod 'TTTAttributedLabel'
pod 'Google-Maps-iOS-SDK'
