platform :ios, '6.0'
pod 'MMDrawerController', '~> 0.5.0'
pod 'AFNetworking'
pod 'MBProgressHUD'
pod 'ISRefreshControl', '~> 1.0.2'
pod 'MWFeedParser', '~> 0.0.1'
pod 'REMenu', '~> 1.5'
pod 'SDWebImage'
